#ifndef _LuaControlInclude_h
#define _LuaControlInclude_h
#pragma once

#include REQUIRE_H(CControlUI)
#include REQUIRE_H(CContainerUI)
#include REQUIRE_H(CHorizontalLayoutUI)
#include REQUIRE_H(CVerticalLayoutUI)
#include REQUIRE_H(CTabLayoutUI)
#include REQUIRE_H(CTileLayoutUI)
#include REQUIRE_H(CChildLayoutUI)
#include REQUIRE_H(CAnimationTabLayoutUI)
#include REQUIRE_H(CActiveXUI)
#include REQUIRE_H(CComboUI)
#include REQUIRE_H(CComboBoxUI)
#include REQUIRE_H(CLabelUI)
#include REQUIRE_H(CTextUI)
#include REQUIRE_H(CDateTimeUI)
#include REQUIRE_H(CProgressUI)
#include REQUIRE_H(CButtonUI)
#include REQUIRE_H(COptionUI)
#include REQUIRE_H(CRadioUI)
#include REQUIRE_H(CCheckBoxUI)
#include REQUIRE_H(CFadeButtonUI)
#include REQUIRE_H(CFadeOptionUI)
#include REQUIRE_H(CFadeCheckBoxUI)
#include REQUIRE_H(CAlbumButtonUI)
#include REQUIRE_H(CAnimControlUI)
#include REQUIRE_H(CEditUI)
#include REQUIRE_H(CFlashUI)
#include REQUIRE_H(CGifAnimUI)
#include REQUIRE_H(CHotKeyUI)
#include REQUIRE_H(CSeqButtonUI)
#include REQUIRE_H(CSliderUI)
#include REQUIRE_H(CScrollBarUI)
#include REQUIRE_H(CListUI)
#include REQUIRE_H(CTreeViewUI)
#include REQUIRE_H(CWebBrowserUI)
#include REQUIRE_H(CWkeWebkitUI)

namespace DuiLib
{
	class RegDuiControls2Lua
	{
	public:
		static void RegModule(lua_State* l)
		{
			LUA_CLASS_REG(CControlUI)
			LUA_CLASS_REG(CContainerUI)
			LUA_CLASS_REG(CHorizontalLayoutUI)
			LUA_CLASS_REG(CVerticalLayoutUI)
			LUA_CLASS_REG(CTileLayoutUI)
			LUA_CLASS_REG(CChildLayoutUI)
			LUA_CLASS_REG(CTabLayoutUI)
			LUA_CLASS_REG(CAnimationTabLayoutUI)
			LUA_CLASS_REG(CActiveXUI)
			LUA_CLASS_REG(CComboUI)
			LUA_CLASS_REG(CComboBoxUI)
			LUA_CLASS_REG(CLabelUI)
			LUA_CLASS_REG(CTextUI)
			LUA_CLASS_REG(CDateTimeUI)
			LUA_CLASS_REG(CProgressUI)
			LUA_CLASS_REG(CButtonUI)
			LUA_CLASS_REG(COptionUI)
			LUA_CLASS_REG(CRadioUI)
			LUA_CLASS_REG(CCheckBoxUI)
			LUA_CLASS_REG(CFadeButtonUI)
			LUA_CLASS_REG(CFadeOptionUI)
			LUA_CLASS_REG(CFadeCheckBoxUI)
			LUA_CLASS_REG(CAlbumButtonUI)
			LUA_CLASS_REG(CAnimControlUI)
			LUA_CLASS_REG(CEditUI)
			LUA_CLASS_REG(CFlashUI)
			LUA_CLASS_REG(CGifAnimUI)
			LUA_CLASS_REG(CHotKeyUI)
			LUA_CLASS_REG(CSeqButtonUI)
			LUA_CLASS_REG(CSliderUI)
			LUA_CLASS_REG(CScrollBarUI)
			LUA_CLASS_REG(CListUI)
			LUA_CLASS_REG(CListBodyUI)
			LUA_CLASS_REG(CListHeaderUI)
			LUA_CLASS_REG(CListHeaderItemUI)
			LUA_CLASS_REG(CListElementUI)
			LUA_CLASS_REG(CListLabelElementUI)
			LUA_CLASS_REG(CListTextElementUI)
			LUA_CLASS_REG(CListContainerElementUI)
			LUA_CLASS_REG(CTreeNodeUI)
			LUA_CLASS_REG(CTreeViewUI)
			LUA_CLASS_REG(CWebBrowserUI)
			LUA_CLASS_REG(CWkeWebkitUI)
		}
	};
}


#endif//_LuaControlInclude_h